#' ChemRICH Analysis Function
#'
#' Conducts ChemRICH analysis for each comparison in a provided result
#' generated by ms_stat_anova() (default) or from a single
#' ChemRICH input (in development). The original enrichment method is adapted
#' from Chemical Similarity Enrichment Analysis (ChemRICH), which is detailed
#' in Barupal et. al. 2017 (DOI: 10.1038/s41598-017-15231-w).
#' Significantly enriched classes are determined by a weighted
#' Kolmogorov-Smirnov Test adjusted for false discovery rate (FDR).
#'
#' @param d_stat Univariate results list generated by ms_stat_anova().
#' @param d_ref Data frame to use for assigning annotation classes.
#' @param cl_name Variable name to use for assigning classes and grouping
#' for enrichment analysis.
#' @return A ChemRICH results data frame.
#' @examples
#' # ms_stat_crich(
#' #   d_stat = d[["stats"]],
#' #   d_ref = d[["data"]][["anno"]],
#' #   cl_name = "label.saturation"
#' # )
#'
#' @export
ms_stat_crich <- function(
  d_stat,
  d_ref,
  cl_name
) {
  # load data
  d1 <- d_stat
  d2 <- d_ref
  cl1 <- cl_name
  # Assign classes from reference
  d3 <- dplyr::left_join(
    d1,
    d2[, c("Name", cl1, "label")],
    by = "Name"
  )
  # Run KS test for each comparison and create separate results df
  cmp1 <- unique(d3[["Comparison.fc"]])
  cr_run <- setNames(
    parallel::mclapply(
      mc.cores = ceiling(parallel::detectCores() * 0.75),
      seq.int(1, length(cmp1), 1),
      function(x) {
        # Extract unique Classes
        cr1 <- unique(d3[[cl1]])
        ## Remove from list if unknown
        cr1 <- cr1[cr1 != "Unknown"]
        # Run KS test for each class
        cr2 <- setNames(
          lapply(
            seq.int(1, length(cr1), 1),
            function(y) {
              # KS test
              ksdf <- ks.test(
                d3[
                  d3[["Comparison.fc"]] == cmp1[[x]] &
                    d3[[cl1]] == cr1[[y]], c("p adj")
                ],
                "punif",
                alternative = "greater"
              )
              # Replace NaN and format output
              ksdf2 <- setNames(data.frame(
                "Comparison.ID" = x,
                "Comparison" = cmp1[[x]],
                "Cluster.ID" = y,
                "Cluster" = cr1[[y]],
                "p.value" = ksdf[["p.value"]]
              ), c("Comparison.ID", "Comparison", "Cluster.ID", cl1, "p.value"))
              ksdf2[is.nan(ksdf2[["p.value"]]), c("p.value")] <- 1
              return(ksdf2)
            }
          ),
          cr1
        )
        cr2 <- dplyr::bind_rows(cr2)
        # FDR
        cr2[["FDR"]] <- p.adjust(
          cr2[["p.value"]],
          method = "fdr"
        )
        # Cluster Size
        cr2 <- dplyr::left_join(
          cr2,
          setNames(
            dplyr::count(
              as.data.frame(
                d3[d3[["Comparison.fc"]] == cmp1[[x]], c(cl1)]
              ),
              as.data.frame(
                d3[d3[["Comparison.fc"]] == cmp1[[x]], c(cl1)]
              )[[1]]
            ),
            c(cl1, "n")
          ),
          by = cl1
        )
        # Inc:Dec Ratio
        cr_rat <- data.frame(
          setNames(
            dplyr::count(
              dplyr::filter(
                setNames(
                  data.frame(
                    cl1 = as.data.frame(
                      d3[
                        d3[["Comparison.fc"]] == cmp1[[x]],
                        c(cl1)
                      ]
                    ),
                    "Ratio" = ifelse(
                      as.data.frame(
                        d3[
                          d3[["Comparison.fc"]] == cmp1[[x]],
                          c("Log2FC")
                        ]
                      ) > 0,
                      "Inc",
                      "Dec"
                    )
                  ),
                  c(cl1, "Ratio")
                ),
                .data[["Ratio"]] == "Inc" # nolint
              ),
              .data[[cl1]]
            ),
            c(
              cl1,
              "Increased"
            )
          )
        )
        cr_rat <- dplyr::full_join(
          cr_rat,
          data.frame(
            setNames(
              dplyr::count(
                dplyr::filter(
                  setNames(
                    data.frame(
                      cl1 = as.data.frame(
                        d3[
                          d3[["Comparison.fc"]] == cmp1[[x]],
                          c(cl1)
                        ]
                      ),
                      "Ratio" = ifelse(
                        as.data.frame(
                          d3[
                            d3[["Comparison.fc"]] == cmp1[[x]],
                            c("Log2FC")
                          ]
                        ) > 0,
                        "Inc",
                        "Dec"
                      )
                    ),
                    c(cl1, "Ratio")
                  ),
                  .data[["Ratio"]] == "Dec" # nolint
                ),
                .data[[cl1]]
              ),
              c(
                cl1,
                "Decreased"
              )
            )
          ),
          by = cl1
        )
        # Combine and finish formatting
        cr3 <- dplyr::left_join(
          cr2,
          cr_rat,
          by = cl1
        )
        cr3[is.na(cr3)] <- 0
        cr3[["Ratio"]] <- ifelse(
          cr3[["Decreased"]] == 0,
          1,
          (cr3[["Increased"]]) /
            (cr3[["Increased"]] +
                cr3[["Decreased"]]
            )
        )
        ## Sort names
        cr3[["sort"]] <- gsub(
          "^.*\\.",
          "",
          cr3[[cl1]]
        )
        cr3 <- cr3[order(cr3[["sort"]]), ]
        cr3 <- cr3[, -ncol(cr3)]
        if(class(cr3[[cl1]]) != "factor") { # nolint
          cr3[[cl1]] <- factor(
            cr3[[cl1]],
            levels = c(cr3[[cl1]])
          )
        }
        cr3 <- dplyr::left_join(
          cr3,
          unique(d3[, c(cl1, "label")]),
          by = cl1
        )
        return(cr3)
      }
    ),
    cmp1
  )
  cr_out <- dplyr::bind_rows(cr_run)
  return(cr_out)
}

#' Plot ChemRICH Results
#'
#' Plots ChemRICH results for selected comparison as a dot plot.
#'
#' @param dfcr An individual comparison from a ChemRICH results data frame.
#' @return A dot plot displaying ChemRICH results,
#' including cluster size, increased/decreased proportion,
#' and statistical significance.
#' @examples
#' # ms_plot_crich(
#' #   dfcr = d[["chemrich"]][d[["chemrich"]][["Comparison"]] == "comp1", ],
#' #   p_title = "comp1"
#' # )
#'
#' @export
ms_plot_crich <- function(
  dfcr
) {
  df <- dfcr
  # Main Plot
  cr_plot <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = df[[4]], # nolint
      y = -log10(FDR), # nolint
      fill = Ratio # nolint
    )
  ) +
    ## Connect lines to significantly altered clusters
    ggplot2::geom_linerange(
      data = df[df[["FDR"]] < 0.05, ],
      ggplot2::aes(
        x = df[df[["FDR"]] < 0.05, 4],
        ymax = -log10(df[df[["FDR"]] < 0.05, "FDR"]),
        ymin = 0
      ),
      color = "black"
    ) +
    ## Plot points
    ggplot2::geom_point(
      shape = 21,
      col = "black",
      ggplot2::aes(
        size = .data[["n"]] # nolint
      ),
      alpha = ifelse(
        df[["FDR"]] < 0.05,
        1,
        0.5
      )
    ) +
    ## Significance line
    ggplot2::geom_hline(
      yintercept = 1.3,
      linetype = "dashed",
      color = col_univ()[[1]] # nolint
    ) +
    ## Theme
    ms_theme1() + # nolint
    ggplot2::theme(plot.margin = grid::unit(
      c(1, 4, 1, 4),
      "cm"
    )) +
    ## Axis labels
    ggplot2::xlab("Class") +
    ggplot2::ylab("-log10(adjusted p-value)") +
    ## Gradient and size scaling
    ggplot2::scale_fill_gradientn(
      name = "Increased Ratio",
      colors = c(
        "midnightblue",
        "royalblue2",
        "white",
        "goldenrod1",
        "firebrick3"
      ),
      breaks = c(
        0, .25, .5, .75, 1
      ),
      labels = c(
        "100% Decreased",
        "25% Increased:75% Decreased",
        "50% Increased:50% Decreased",
        "75% Increased:25% Decreased",
        "100% Increased"
      )
    ) +
    ggplot2::scale_size_area(
      name = "Cluster Size",
      max_size = 16
    )
  return(cr_plot)
}
