#' Volcano Plot
#'
#' Generates a volcano plot from a statistical results object for
#' a chosen comparison.
#'
#' @param d_stat Univariate results list generated by ms_stat_anova().
#' @param comp_name Comparison name, provided as a character string.
#' @param diff_col Column name containing effect size.
#' @param p_col Column name containing adjusted p-values.
#' @param p_cut Numeric value for p-value cutoff to indicate significance.
#' @param f_cut Fold change cutoff indicating high effect size.
#' @param f_lim Numeric value for fold change limits on the x-axis.
#' @param y_limit Upper-bound -log10 p-value to display on the y-axis.
#' @param x_title X-axis legend title, provided as a character string.
#' @return A volcano plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_volcano(
#' #   d_stat = d[["stats"]],
#' #   comp_name = "KO vs. Control",
#' #   diff_col = "Log2FC",
#' #   p_col = "p adj",
#' #   p_cut = 0.05,
#' #   f_cut = 0.25,
#' #   f_lim = 6,
#' #   y_limit = 10,
#' #   x_title = "x-axis title"
#' # )
#'
#' @export
ms_plot_volcano <- function(
  d_stat,
  comp_name,
  diff_col,
  p_col,
  p_cut,
  f_cut,
  f_lim,
  y_limit,
  x_title
) {
  # Subset Input data
  ld <- d_stat
  ld <- ld[ld[["Comparison"]] == comp_name, ]
  # Plot function
  v <- EnhancedVolcano::EnhancedVolcano(
    ld,
    lab = ld[["Name"]],
    title = ggplot2::element_blank(),
    subtitle = ggplot2::element_blank(),
    caption = ggplot2::element_blank(),
    x = diff_col,
    y = p_col,
    pCutoff = p_cut,
    FCcutoff = f_cut,
    cutoffLineType = "twodash",
    legendLabels = c("NS", "Fold Change",
                     "p-value", "FC+P"),
    legendLabSize = 12,
    labFace = "bold",
    col = ggsci::pal_npg("nrc")(10)[c(4, 3, 5, 8)],
    colAlpha = 0.7,
    legendIconSize = 4,
    pointSize = 2,
    border = "full",
    borderWidth = 1.5,
    legendPosition = "'right'",
    labSize = 3,
    drawConnectors = TRUE,
    max.overlaps = 10,
    typeConnectors = "open",
    min.segment.length = ggplot2::unit(
      1,
      "mm"
    )
  ) +
    ms_theme1() + # nolint
    ggplot2::labs(color = "Key") +
    ggplot2::labs(
      color = "Key",
      x = x_title,
      y = paste("-log10 P-value (FDR)")
    ) +
    ggplot2::theme(plot.margin = ggplot2::unit(c(.2, .2, .2, .2), "cm")) +
    ggplot2::coord_cartesian(xlim = c(-f_lim, f_lim),
                             ylim = c(0, y_limit)) +
    ggplot2::scale_x_continuous(breaks = seq(-f_lim, f_lim, (f_lim / 4)))
  return(v)
}

#' Heatmap 1
#'
#' Generates a heatmap from a statistical results object for
#' a vector of comparisons.
#'
#' @param d_stat Univariate results list generated by ms_stat_anova().
#' @param d_ref Reference annotation list generated by ms_input().
#' @param c_list Comparison list, provided as a vector.
#' @param diff_col Column name containing effect size.
#' @param p_col Column name containing adjusted p-values.
#' @param an1 Variable names used for annotating the heatmap.
#' @param hm_w Heatmap width.
#' @param hm_h Heatmap height.
#' @param fs_r Row fontsize.
#' @param cl_c Logical indicating if the columns should be clustered.
#' @param cl_r Logical indicating if the rows should be clustered.
#' @return A heatmap for the selected comparisons.
#' @examples
#'
#' # ms_plot_heat(
#' #   d_stat = d[["stats"]],
#' #   d_ref = d[["data"]][["anno"]],
#' #   c_list = c("KO vs. Control"),
#' #   diff_col = "Log2FC",
#' #   p_col = "FDR",
#' #   an1 = c("Major.Class", "Saturation"),
#' #   hm_w = 36,
#' #   hm_h = 10,
#' #   fs_r = 8,
#' #   cl_c = TRUE,
#' #   cl_r = TRUE
#' # )
#'
#' @export
ms_plot_heat <- function(
  d_stat, d_ref, c_list, diff_col,
  p_col, an1, hm_w, hm_h, fs_r,
  cl_c, cl_r
) {
  # Load and subset data
  hd1 <- d_stat
  href <- d_ref
  hm_list <- c_list
  an2 <- an1
  hm_in <- hd1[hd1[["Comparison.fc"]] %in% hm_list, ]
  # Format and prepare FC and P matrices
  hd <- reshape2::dcast(
    hm_in[, c(diff_col, "Comparison.fc", "Name")],
    Comparison.fc ~ Name,
    value.var = diff_col
  )
  hp <- reshape2::dcast(
    hm_in[, c(p_col, "Comparison.fc", "Name")],
    Comparison.fc ~ Name,
    value.var = p_col
  )
  hd_in <- as.matrix(hd[, 2:ncol(hd)])
  rownames(hd_in) <- hd[[1]]
  hd_in[is.na(hd_in)] <- max(hd_in[!is.na(hd_in)])
  hp_in <- as.matrix(hp[, 2:ncol(hp)])
  rownames(hp_in) <- hp[[1]]
  hp_in[is.na(hp_in)] <- min(hp_in[!is.na(hp_in)])
  # Figure annotations, colors, and scales
  qs <- quantile(
    hd_in,
    probs = c(
      0.05,
      0.95
    ),
    na.rm = TRUE
  )
  fun_hm_col <- circlize::colorRamp2(
    c(
      qs[[1]],
      (qs[[1]]) / 2,
      (qs[[2]]) / 2,
      qs[[2]]
    ),
    colors = c(
      col_grad()[[1]], # nolint
      col_grad()[[3]],
      "grey",
      col_grad()[[12]]
    )
  )
  if(missing(an2) == FALSE) { # nolint
    fun_hm_bar <- list(
      "Class" = setNames(
        col_univ()[1:length(unique(href[[an2[[1]]]]))], # nolint
        as.character(unique(href[[an2[[1]]]]))
      ),
      "Saturation" = setNames(
        col_univ()[1:length(unique(href[[an2[[2]]]]))], # nolint
        as.character(unique(unique(href[[an2[[2]]]])))
      )
    )
    ### Annotations
    hm_anno_list <- list(
      "column1" = ComplexHeatmap::HeatmapAnnotation(
        `Class` = (href[[an2[[1]]]]),
        `Saturation` = (href[[an2[[2]]]]),
        col = fun_hm_bar,
        show_annotation_name = FALSE
      )
    )
    # Create Plot
    h_out <- ComplexHeatmap::Heatmap(
      hd_in,
      # p-value filter
      layer_fun = function(j, i, x, y, w, h, fill) {
        # map positions of fold change matrix cells onto pvalue heatmap
        p_pos <- ComplexHeatmap::pindex(hp_in, i, j)
        # filter non-significant p values to fill in blanks
        p_blank <- p_pos > 0.05
        # create matrix for subsetting the heatmap
        # to display only significant cells
        p <- ComplexHeatmap::restore_matrix(j, i, x, y) # nolint
        # mask non-significant genes
        grid::grid.rect(
          x[p_blank],
          y[p_blank],
          w,
          h,
          gp = grid::gpar(col = "white")
        )
      },
      col = fun_hm_col,
      top_annotation = hm_anno_list[[1]],
      name = "Log2-Fold Change",
      show_column_names = FALSE,
      show_row_names = TRUE,
      heatmap_width = ggplot2::unit(hm_w, "cm"),
      heatmap_height = ggplot2::unit(hm_h, "cm"),
      row_names_side = "left",
      row_names_gp = grid::gpar(fontsize = fs_r),
      cluster_columns = cl_c,
      cluster_rows = cl_r
    )
  }
  if(missing(an2) == TRUE) { # nolint
    # Create Plot
    h_out <- ComplexHeatmap::Heatmap(
      hd_in,
      # p-value filter
      layer_fun = function(j, i, x, y, w, h, fill) {
        # map positions of fold change matrix cells onto pvalue heatmap
        p_pos <- ComplexHeatmap::pindex(hp_in, i, j)
        # filter non-significant p values to fill in blanks
        p_blank <- p_pos > 0.05
        # create matrix for subsetting the heatmap
        # to display only significant cells
        p <- ComplexHeatmap::restore_matrix(j, i, x, y) # nolint
        # mask non-significant genes
        grid::grid.rect(
          x[p_blank],
          y[p_blank],
          w,
          h,
          gp = grid::gpar(col = "white")
        )
      },
      col = fun_hm_col,
      name = "Log2-Fold Change",
      show_column_names = FALSE,
      show_row_names = TRUE,
      heatmap_width = ggplot2::unit(hm_w, "cm"),
      heatmap_height = ggplot2::unit(hm_h, "cm"),
      row_names_side = "left",
      row_names_gp = grid::gpar(fontsize = fs_r),
      cluster_columns = cl_c,
      cluster_rows = cl_r
    )
  }
  return(h_out)
}

#' Lipid Network Plot
#'
#' Generates a network plot using known lipid metabolism pathways
#' to visualize class-based enrichment statistics. Uses a manually
#' curated collection of pathways as a reference. Lipid class
#' annotations assigned by this reference enable mapping of any
#' untargeted or targeted lipidomics dataset onto the network.
#'
#' @param d_enrch Enrichment results list generated by ms_stat_crich().
#' Only required when network type is "annotation" or "enrichment".
#' @param net_type Output network type. Currently supported types are
#' "pathways_legend", "base", "annotation", or "enrichment".
#' @param cl_var Clustering variable to use for aggregating lipid classes.
#' @param comp1 Comparison name for plotting enrichment statistics. Currently
#' supports up to one comparison name.
#' @param comp_sat Should unsaturated and saturated lipid classes be compared?
#' Enter a logical value (TRUE/FALSE) to toggle lipid saturation comparisons.
#' This parameter is dependent upon the presence of both unsaturated and
#' saturated lipid classes in the enrichment statistics data frame.
#' @return A network plot of the specified type.
#' @examples
#'
#' # ## Pathway Legend
#' # ms_plot_lipidnet(
#' #   net_type = "pathways_legend"
#' # )
#' # ## Base network
#' # ms_plot_lipidnet(
#' #   net_type = "base"
#' # )
#' # ## Plot dataset annotations
#' # ms_plot_lipidnet(
#' #   d_enrch = d[["chemrich"]],
#' #   net_type = "annotation",
#' #   cl_var = "label_saturation"
#' # )
#' # ## Plot dataset enrichment results
#' # ms_plot_lipidnet(
#' #   d_enrch = d[["chemrich"]],
#' #   net_type = "enrichment",
#' #   cl_var = "label_saturation",
#' #   comp1 = "HFA_F-BR",
#' #   comp_sat = TRUE
#' # )
#'
#' @export
ms_plot_lipidnet <- function( # nolint
  d_enrch = NULL,
  net_type,
  cl_var = NULL,
  comp1 = NULL,
  comp_sat = NULL
) {
  # Retrieve network information from database
  net_nodes <- DBI::dbGetQuery(
    db1, # nolint
    'select * from lipid_nodes' # nolint
  )
  net_nodes[["x_man"]] <- as.numeric(net_nodes[["x_man"]])
  net_nodes[["y_man"]] <- as.numeric(net_nodes[["y_man"]])
  ## Edges
  net_edges <- DBI::dbGetQuery(
    db1, # nolint
    'select * from lipid_edges' # nolint
  )
  net_plot_lay2 <- DBI::dbGetQuery(
    db1, # nolint
    'select * from lipid_edges_pw' # nolint
  )
  net_plot_lay2[["x"]] <- as.numeric(net_plot_lay2[["x"]])
  net_plot_lay2[["y"]] <- as.numeric(net_plot_lay2[["y"]])

  # Pathway legend only
  if(net_type == "pathways_legend") { # nolint
    # Create network
    net_plot <- igraph::graph_from_data_frame(
      net_edges,
      vertices = net_nodes
    )
    net_plot_lay <- ggraph::create_layout(net_plot, layout = "stress")
    net_plot_lay[["x"]] <- net_plot_lay[["x_man"]]
    net_plot_lay[["y"]] <- net_plot_lay[["y_man"]]
    # Plot
    net_plot2 <- ggraph::ggraph(
      net_plot_lay
    ) +
      # Boundary polygon for distinguishing different pathways
      ggplot2::geom_polygon(
        data = net_plot_lay2,
        ggplot2::aes(
          x = net_plot_lay2[["x"]],
          y = net_plot_lay2[["y"]],
          fill = net_plot_lay2[["synthesis_pathway"]]
        ),
        alpha = 0.5,
        color = "grey25",
        show.legend = TRUE
      ) +
      ggplot2::scale_fill_manual(
        "Pathway",
        values = col_univ()
      ) +
      ms_theme1() +
      ms_theme_net2()
  }
  # Base network
  if(net_type == "base") { # nolint
    # Create network
    net_plot <- igraph::graph_from_data_frame(
      net_edges,
      vertices = net_nodes
    )
    net_plot_lay <- ggraph::create_layout(net_plot, layout = "stress")
    net_plot_lay[["x"]] <- net_plot_lay[["x_man"]]
    net_plot_lay[["y"]] <- net_plot_lay[["y_man"]]
    ## Plot
    net_plot2 <- ggraph::ggraph(
      net_plot_lay
    ) +
      # Boundary polygon for distinguishing different pathways
      ggplot2::geom_polygon(
        data = net_plot_lay2,
        ggplot2::aes(
          x = net_plot_lay2[["x"]],
          y = net_plot_lay2[["y"]],
          fill = net_plot_lay2[["synthesis_pathway"]]
        ),
        alpha = 0.5,
        color = "grey25",
        show.legend = FALSE
      ) +
      # node points
      ggraph::geom_node_point() +
      # edge attributes
      ggraph::geom_edge_link(
        ggplot2::aes(label = .data[["enzyme_id"]]), # nolint
        label_dodge = ggplot2::unit(2, "mm"),
        angle_calc = "along",
        alpha = 0.8,
        color = "grey50"
      ) +
      # color scheme
      ggplot2::scale_fill_manual(
        "Pathway",
        values = col_univ()
      ) +
      # text labels
      ggrepel::geom_text_repel(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["label"]]
        ),
        bg.color = "white",
        bg.r = 0.05,
        alpha = 0.6,
        nudge_x = 0.25,
        nudge_y = 0.1,
        size = 5
      ) +
      # plot theme
      ms_theme1() +
      ms_theme_net()
  }

  ## Annotation network
  if(net_type == "annotation") { # nolint
    net1 <- d_enrch
    # Map dataset annotations
    net_anno <- setNames(aggregate(
      unique(net1[, c(cl_var, "n", "label")])[["n"]], # nolint
      list(unique(net1[, c(cl_var, "n", "label")])[["label"]]),
      function(x) sum(x)
    ), c("label", "cluster_size"))
    ## Adjust node attributes
    net_nodes <- dplyr::left_join(
      net_nodes,
      net_anno,
      by = "label"
    )
    net_nodes[["cluster_size"]] <- ifelse(
      is.na(net_nodes[["cluster_size"]]),
      0,
      net_nodes[["cluster_size"]]
    )
    net_nodes[["set_alpha"]] <- (
      (net_nodes[["cluster_size"]] - min(net_nodes[["cluster_size"]])) /
        (max(net_nodes[["cluster_size"]])) - min(net_nodes[["cluster_size"]])
    )
    net_nodes[["set_clus_size"]] <- (
      (net_nodes[["cluster_size"]] - min(net_nodes[["cluster_size"]])) /
        (max(net_nodes[["cluster_size"]])) - min(net_nodes[["cluster_size"]])
    )
    ## Adjust edge attributes
    net_edges[["set_alpha_edge"]] <- ifelse(
      net_edges[["from"]] %in%
        net_nodes[net_nodes[["set_clus_size"]] > 0, "Node"],
      1,
      0.25
    )
    # Network
    net_plot <- igraph::graph_from_data_frame(
      net_edges,
      vertices = net_nodes
    )
    net_plot_lay <- ggraph::create_layout(net_plot, layout = "stress")
    net_plot_lay[["x"]] <- net_plot_lay[["x_man"]]
    net_plot_lay[["y"]] <- net_plot_lay[["y_man"]]
    # Plot
    net_plot2 <- ggraph::ggraph(
      net_plot_lay
    ) +
      # Boundary polygon for distinguishing different pathways
      ggplot2::geom_polygon(
        data = net_plot_lay2,
        ggplot2::aes(
          x = net_plot_lay2[["x"]],
          y = net_plot_lay2[["y"]],
          fill = net_plot_lay2[["synthesis_pathway"]]
        ),
        alpha = 0.5,
        color = "grey25",
        show.legend = FALSE
      ) +
      # edge attributes
      ggraph::geom_edge_link(
        ggplot2::aes(
          label = ifelse(
            .data[["set_alpha_edge"]] == 0.25, # nolint
            "",
            .data[["enzyme_id"]]
          ),
          alpha = .data[["set_alpha_edge"]]
        ),
        label_dodge = ggplot2::unit(2, "mm"),
        label_alpha = 0.5,
        angle_calc = "along",
        color = "grey50",
        show.legend = FALSE
      ) +
      # node points
      ggraph::geom_node_point(
        ggplot2::aes(
          alpha = ifelse(
            .data[["set_alpha"]] == 0, # nolint
            1,
            0
          )
        ),
        color = "grey50",
        show.legend = FALSE
      ) +
      ggraph::geom_node_point(
        ggplot2::aes(
          size = .data[["cluster_size"]] * 1
        ),
        show.legend = FALSE
      ) +
      # color scheme
      ggplot2::scale_fill_manual(
        "Pathway",
        values = col_univ()
      ) +
      ggplot2::scale_size_area(
        max_size = 16
      ) +
      # text labels
      ggrepel::geom_text_repel(
        ggplot2::aes(
          x = .data[["x"]],
          y = .data[["y"]],
          label = .data[["label"]]
        ),
        bg.color = "white",
        bg.r = 0.05,
        alpha = 0.6,
        nudge_x = 0.25,
        nudge_y = 0.1,
        size = 5
      ) +
      # plot theme
      ms_theme1() +
      ms_theme_net()
  }

  # Enrichment network
  if(net_type == "enrichment") { # nolint
    net1 <- d_enrch
    # Map dataset annotations
    net_anno <- setNames(aggregate(
      unique(net1[, c(cl_var, "n", "label")])[["n"]], # nolint
      list(unique(net1[, c(cl_var, "n", "label")])[["label"]]),
      function(x) sum(x)
    ), c("label", "cluster_size"))
    ## Adjust node attributes
    net_nodes <- dplyr::left_join(
      net_nodes,
      net_anno,
      by = "label"
    )
    net_nodes[["cluster_size"]] <- ifelse(
      is.na(net_nodes[["cluster_size"]]),
      0,
      net_nodes[["cluster_size"]]
    )
    net_nodes[["set_alpha"]] <- (
      (net_nodes[["cluster_size"]] - min(net_nodes[["cluster_size"]])) /
        (max(net_nodes[["cluster_size"]])) - min(net_nodes[["cluster_size"]])
    )
    net_nodes[["set_clus_size"]] <- (
      (net_nodes[["cluster_size"]] - min(net_nodes[["cluster_size"]])) /
        (max(net_nodes[["cluster_size"]])) - min(net_nodes[["cluster_size"]])
    )
    ## Adjust edge attributes
    net_edges[["set_alpha_edge"]] <- ifelse(
      net_edges[["from"]] %in%
        net_nodes[net_nodes[["set_clus_size"]] > 0, "Node"],
      1,
      0.25
    )
    # Map enrichment statistics
    ## Join enrichment results with network plot
    if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
      net1[["Saturation"]] <- ifelse(
        grepl("Uns|uns", net1[[cl_var]]),
        "Unsat",
        "Sat"
      )
      cmp <- comp1
      net_enrch <- tidyr::pivot_wider(
        net1[, c( # nolint
          "Comparison", "label", "Saturation",
          "Ratio", "FDR", "n"
        )],
        names_from = c(.data[["Comparison"]], .data[["Saturation"]]), # nolint
        values_from = c(.data[["Ratio"]], .data[["FDR"]], .data[["n"]])
      )
      net_name1 <- names(net_enrch[, 2:ncol(net_enrch)]) # nolint
      net_nodes <- dplyr::left_join(
        net_nodes,
        net_enrch,
        by = "label"
      )
      ## Network
      net_plot <- igraph::graph_from_data_frame(
        net_edges,
        vertices = net_nodes
      )
      ## Network layout
      net_plot_lay <- ggraph::create_layout(net_plot, layout = "stress")
      net_plot_lay[["x"]] <- net_plot_lay[["x_man"]]
      net_plot_lay[["y"]] <- net_plot_lay[["y_man"]]
      # Plot
      net_plot2 <- ggraph::ggraph(
        net_plot_lay
      ) +
        # color scheme
        ggplot2::scale_color_manual(
          "Pathway",
          values = col_univ()
        ) +
        ggplot2::scale_fill_manual(
          "Pathway",
          values = col_univ()
        ) +
        # Boundary polygon for distinguishing different pathways
        ggplot2::geom_polygon(
          data = net_plot_lay2,
          ggplot2::aes(
            x = net_plot_lay2[["x"]],
            y = net_plot_lay2[["y"]],
            fill = net_plot_lay2[["synthesis_pathway"]]
          ),
          alpha = 0.5,
          color = "grey25",
          show.legend = FALSE
        ) +
        # edge attributes
        ggraph::geom_edge_link(
          ggplot2::aes(
            label = ifelse(
              .data[["set_alpha_edge"]] == 0.25, # nolint
              "",
              .data[["enzyme_id"]]
            ),
            alpha = .data[["set_alpha_edge"]]
          ),
          label_dodge = ggplot2::unit(2, "mm"),
          label_alpha = 0.5,
          angle_calc = "along",
          color = "grey50",
          show.legend = FALSE
        ) +
        # Background for node panels
        ggplot2::geom_rect(
          ggplot2::aes(
            xmin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x - 0.25 # nolint
            ),
            ymin = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y - 0.25 # nolint
            ),
            ymax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              y + 0.15
            ),
            xmax = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              x + 0.25
            )
          ),
          alpha = 0.9,
          fill = "grey",
          color = "grey25",
          show.legend = FALSE
        ) +
        # node points
        ggraph::geom_node_point(
          ggplot2::aes(
            alpha = ifelse(
              .data[["set_alpha"]] == 0, # nolint
              1,
              0
            )
          ),
          color = "grey75",
          show.legend = FALSE
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggnewscale::new_scale_fill() +
        ## Enrichment nodes
        # ChemRICH nodes
        ggraph::geom_node_point(
          ggplot2::aes(
            size = ifelse(
              is.na(.data[[paste(
                "n", cmp, "Sat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "n", cmp, "Sat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0,
              sqrt(as.numeric(unlist(.data[[paste(
                "n", cmp, "Sat", sep = "_"
              )]])))
            ),
            fill = ifelse(
              is.na(.data[[paste(
                "Ratio", cmp, "Sat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Ratio", cmp, "Sat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0.5,
              unlist(.data[[paste(
                "Ratio", cmp, "Sat", sep = "_"
              )]])
            ),
            color = ifelse(
              is.na(.data[[paste(
                "Ratio", cmp, "Sat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Ratio", cmp, "Sat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              "b",
              "a"
            )
          ),
          position = ggplot2::position_nudge(
            x = -0.1,
            y = -0.05
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggraph::geom_node_point(
          ggplot2::aes(
            size = ifelse(
              is.na(.data[[paste(
                "n", cmp, "Unsat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "n", cmp, "Unsat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0,
              sqrt(as.numeric(unlist(.data[[paste(
                "n", cmp, "Unsat", sep = "_"
              )]])))
            ),
            fill = ifelse(
              is.na(.data[[paste(
                "Ratio", cmp, "Unsat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Ratio", cmp, "Unsat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              0.5,
              unlist(.data[[paste(
                "Ratio", cmp, "Unsat", sep = "_"
              )]])
            ),
            color = ifelse(
              is.na(.data[[paste(
                "Ratio", cmp, "Unsat", sep = "_"
              )]]) |
                unlist(
                  lapply(
                    .data[[paste(
                      "Ratio", cmp, "Unsat", sep = "_"
                    )]],
                    function(x) is.null(x)
                  )
                ),
              "b",
              "a"
            )
          ),
          position = ggplot2::position_nudge(
            x = 0.1,
            y = -0.05
          ),
          shape = 21,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = c("black", "white")
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        # ChemRICH node labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = ifelse(
              unlist(
                lapply(
                  .data[[paste("n", cmp, "Sat", sep = "_")]],
                  function(x) is.null(x)
                )
              ),
              "",
              "Sat."
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.2
            )
          ),
          nudge_x = -0.1,
          nudge_y = -0.15,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = ifelse(
              unlist(
                lapply(
                  .data[[paste("n", cmp, "Unsat", sep = "_")]],
                  function(x) is.null(x)
                )
              ),
              "",
              "Unsat."
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.2
            )
          ),
          nudge_x = 0.1,
          nudge_y = -0.15,
          color = "white",
          bg.color = "grey25",
          show.legend = FALSE
        ) +
        # ChemRICH node FDR labels
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Sat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.2
            )
          ),
          nudge_x = -0.1,
          nudge_y = -0.2,
          color = "white",
          bg.color = "grey10",
          show.legend = FALSE
        ) +
        shadowtext::geom_shadowtext(
          ggplot2::aes(
            x = x,
            y = y,
            label = unlist(
              lapply(
                .data[[paste("FDR", cmp, "Unsat", sep = "_")]],
                function(x) {
                  d1 <- ifelse(
                    !is.null(x),
                    x > 0.05 | is.na(x),
                    TRUE
                  )
                  d1 <- ifelse(
                    d1 == FALSE,
                    paste("FDR = ", round(x, digits = 4)),
                    ""
                  )
                  return(d1)
                }
              )
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0,
              0.2
            )
          ),
          nudge_x = 0.1,
          nudge_y = -0.2,
          color = "white",
          bg.color = "grey10",
          show.legend = FALSE
        ) +
        # Increased ratio color scale
        ggplot2::scale_fill_gradientn(
          "Increased Ratio",
          colors = c(
            "dodgerblue4",
            "azure",
            "firebrick3"
          )
        ) +
        ## Change scale
        ggnewscale::new_scale_color() +
        ggplot2::scale_size_area(
          max_size = 16
        ) +
        # text labels
        ggrepel::geom_text_repel(
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            label = .data[["label"]],
            alpha = ifelse(
              .data[["cluster_size"]] == 0,
              0.1,
              1
            ),
            size = ifelse(
              .data[["cluster_size"]] == 0,
              0.05,
              0.25
            )
          ),
          color = "black",
          bg.r = 0.01,
          bg.color = "white",
          nudge_x = 0,
          nudge_y = 0.1 * 1,
          show.legend = FALSE
        ) +
        ggplot2::scale_color_manual(
          "Pathway",
          values = col_univ()
        ) +
        # plot theme
        ms_theme1() +
        ms_theme_net()
    }
    #   if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
    # }
    # if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
    # }
    # if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
    # }
    # if(length(comp1) == 1 && comp_sat == TRUE) { # nolint
    # }
  }
  return(net_plot2)
}
